### ISSUE TITLE
fluentd container exiting immediately

### ISSUE THREAD

**Issue by g3kr** [digikin/fluentd-elastic-kibana#7]
I am having the exact setup suggested here. All containers except fluentd comes up. This is the logs from the fluentd container

```
2022-05-27 22:37:04 +0000 [info]: parsing config file is succeeded path="/fluentd/etc/fluent.conf"
2022-05-27 22:37:04 +0000 [info]: gem 'fluent-plugin-elasticsearch' version '5.0.3'
2022-05-27 22:37:04 +0000 [info]: gem 'fluentd' version '1.12.0'
/usr/local/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- elasticsearch/transport/transport/connections/selector (LoadError)
        from /usr/local/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from /usr/local/bundle/gems/fluent-plugin-elasticsearch-5.0.3/lib/fluent/plugin/elasticsearch_fallback_selector.rb:1:in `<top (required)>'
        from /usr/local/bundle/gems/fluent-plugin-elasticsearch-5.0.3/lib/fluent/plugin/out_elasticsearch.rb:31:in `require_relative'
        from /usr/local/bundle/gems/fluent-plugin-elasticsearch-5.0.3/lib/fluent/plugin/out_elasticsearch.rb:31:in `<top (required)>'
        from /usr/local/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from /usr/local/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from /usr/local/bundle/gems/fluentd-1.12.0/lib/fluent/registry.rb:102:in `block in search'
```
Has anyone experienced this? How do I resolve this?

**Comment by g3kr** [comment]
https://github.com/fluent/fluentd-docs-gitbook/issues/391#issuecomment-1099085824

The fix was explained here.
