### ISSUE TITLE
fleuntd not starting

### ISSUE THREAD

**Issue by Nguimjeu** [digikin/fluentd-elastic-kibana#8]
When I try to run this project, the `fluentd` container fails to start. The error is the following:

```bash
/usr/local/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- elasticsearch/transport/transport/connections/selector (LoadError)
2023-01-28T14:08:16.859562828Z 	from /usr/local/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
...

```

**Comment by Dilrong** [comment]
[fluent-plugin-elasticsearch/issues/944](https://github.com/uken/fluent-plugin-elasticsearch/issues/944)
It's good to refer to the issue here.

**Comment by digikin** [comment]
Hey @Nguimjeu.  Thanks for creating an issue but I am just a random person contributing back to the docs not a maintainer. Do you have a pull request to fix the above issue?

**Comment by Nguimjeu** [comment]
Hello @digikin,

> Do you have a pull request to fix the above issue?

I have not created a PR for this issue.

**Comment by digikin** [comment]
I did a local build and everything seems to work fine?
```
eric@xps15:~/Documents/github/fluentd-elastic-kibana$ cat /etc/os-release 
PRETTY_NAME="Ubuntu 22.04.2 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.2 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy
```
```
eric@xps15:~/Documents/github/fluentd-elastic-kibana$ docker-compose up -d
Creating network "fluentd-elastic-kibana_default" with the default driver
Pulling elasticsearch (docker.elastic.co/elasticsearch/elasticsearch:7.13.1)...
7.13.1: Pulling from elasticsearch/elasticsearch
ddf49b9115d7: Pull complete
b37635510c69: Pull complete
d67ee5f857b8: Pull complete
c5d9d81d8a16: Pull complete
d81dddc95dea: Pull complete
06e607a1d17d: Pull complete
0137ad2dfac5: Pull complete
Digest: sha256:023ca4452987fb9bd7c661a041435df48c3244bda8473a68151fe52d886c2945
Status: Downloaded newer image for docker.elastic.co/elasticsearch/elasticsearch:7.13.1
Building fluentd
Sending build context to Docker daemon  3.584kB
Step 1/4 : FROM fluent/fluentd:v1.12.0-debian-1.0
v1.12.0-debian-1.0: Pulling from fluent/fluentd
6ec7b7d162b2: Pull complete 
0e2ec621a702: Pull complete 
308aef190730: Pull complete 
18f0c8a8daad: Pull complete 
6a45dbb6ba9f: Pull complete 
5863de6866d3: Pull complete 
6680de879998: Pull complete 
a6e90159173a: Pull complete 
2570037035ec: Pull complete 
Digest: sha256:a44d848390d7b81ddda4a92af96ba65d7d84b028d494bf083d6a1b0be75005c4
Status: Downloaded newer image for fluent/fluentd:v1.12.0-debian-1.0
 ---> 9c3c00d2a1d1
Step 2/4 : USER root
 ---> Running in 28bf48f787ed
Removing intermediate container 28bf48f787ed
 ---> f6b62275f406
Step 3/4 : RUN ["gem", "install", "fluent-plugin-elasticsearch", "--no-document", "--version", "5.0.3"]
 ---> Running in d1651ce31324
Successfully installed multi_json-1.15.0
Successfully installed elasticsearch-api-8.7.0
Successfully installed ruby2_keywords-0.0.5
Successfully installed faraday-net_http-3.0.2
Successfully installed faraday-2.7.4
Successfully installed elastic-transport-8.2.1
Successfully installed elasticsearch-8.7.0
Successfully installed excon-0.99.0
Successfully installed fluent-plugin-elasticsearch-5.0.3
9 gems installed
Removing intermediate container d1651ce31324
 ---> f4d8266caf84
Step 4/4 : USER fluent
 ---> Running in c320643662f2
Removing intermediate container c320643662f2
 ---> 5254567842af
Successfully built 5254567842af
Successfully tagged fluentd-elastic-kibana_fluentd:latest
WARNING: Image for service fluentd was built because it did not already exist. To rebuild this image you must use `docker-compose build` or `docker-compose up --build`.
Pulling web (httpd:)...
latest: Pulling from library/httpd
f1f26f570256: Pull complete
a6b093ae1967: Pull complete
6b400bbb27df: Pull complete
6e310dd059b6: Pull complete
471cb5914961: Pull complete
Digest: sha256:4055b18d92fd006f74d4a2aac172a371dc9a750eaa78000756dee55a9beb4625
Status: Downloaded newer image for httpd:latest
Pulling kibana (docker.elastic.co/kibana/kibana:7.13.1)...
7.13.1: Pulling from kibana/kibana
ddf49b9115d7: Already exists
958849c1178c: Pull complete
2250c02d6170: Pull complete
3bcb539501b5: Pull complete
95cc07b1d68c: Pull complete
4dd1b7549bfa: Pull complete
c0465d29375b: Pull complete
09a56f862c81: Pull complete
602dd9ea24f9: Pull complete
1fdaacdf935f: Pull complete
0dd931b7c853: Pull complete
60b4242aa44a: Pull complete
83260c9d7df6: Pull complete
Digest: sha256:f2dee2c1040e87321c0d99048f1983c9cda2ac43158823362b5a053057dcc202
Status: Downloaded newer image for docker.elastic.co/kibana/kibana:7.13.1
Creating elasticsearch ... done
Creating fluentd-elastic-kibana_kibana_1  ... done
Creating fluentd-elastic-kibana_fluentd_1 ... done
Creating fluentd-elastic-kibana_web_1     ... done
```

**Comment by Nguimjeu** [comment]
@digikin I'll give it a try again and report back to this ticket. Thanks
